name: CI

on:
    push:
        branches:
            - main
            - dev
    pull_request:
        branches:
            - main
            - dev
    
    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    
    Linting:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
        
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
                    
            -   uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip

            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    make dev

            -   name: Lint with isort, black, docformatter, flake8
                run: |
                    make lint

    Typing:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip

            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    make dev

            -   name: Static analysis with pyright
                run: |
                    make type

    Pytests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.8', '3.9', '3.10', '3.11']
                dependencies: ['dev', 'full']

        steps:
            -   uses: actions/checkout@v2
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}
                    
            -   uses: actions/cache@v2
                with:
                    path: ~/.cache/pip
                    key: ${{ runner.os }}-pip

            -   name: Install Dependencies
                run: |
                    python -m pip install --upgrade pip
                    make ${{ matrix.dependencies }}

            -   name: Run Pytests
                run: |
                    make test-cov

            -   name: Upload to codecov.io
                uses: codecov/codecov-action@v3
                with:
                    token: ${{ secrets.CODECOV_TOKEN }}
                    file: ./coverage.xml
                    flags: unittests
                    name: codecov-umbrella
                    fail_ci_if_error: true
