name: Notebook Execution and Error Check

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:  # This enables manual triggering

jobs:
  execute_notebooks:
    runs-on: ubuntu-latest
    
    env:
      COHERE_API_KEY: ${{ secrets.COHERE_API_KEY }}
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}


    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.x

    - name: Poetry cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: poetry-cache-${{ runner.os }}-${{ steps.setup_python.outputs.python-version }}-${{ env.POETRY_VERSION }}

    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Install dependencies
      run: make full; pip install jupyter nbconvert; pip install .

    - name: Execute notebooks and check for errors
      run: |
        cd docs/examples
        for notebook in $(ls *.ipynb); do
          jupyter nbconvert --to notebook --execute "$notebook"
          if [ $? -ne 0 ]; then
            echo "Error found in $notebook"
            exit 1
          fi
        done
